version: '{build}'
environment:
  COVERALLSAPIKEY:
    secure: mNauLxB5TbdrD5SrYX4xR2F+hZTVYXaK1faA+6Zyq6Q+0stUBjl4NqXxLZZCcPO5
build_script:
- ps: .\build.ps1 -target=CoveragePublish -configuration=Debug "-coverallsApiKey=$env:COVERALLSAPIKEY"
test: off
